### ISSUE TITLE
README: fix local server URL

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account#4]
![welcome-to-open-source-atlanta](https://cloud.githubusercontent.com/assets/39992/13732817/58766428-e960-11e5-8496-c65891ad0835.png)

**This issue is reserved for participants of [Welcome to Open Source, Atlanta](http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/)**.
If it’s still available after April 2nd, it’s all yours :)

---
### :bug: The Bug

In the [demo section of this repository’s README](https://github.com/hoodiehq/hoodie-account/blob/master/README.md#demo) is a typo. Instead of `http://localhost::4663` it should say `http://localhost:4663`, with a single `:`
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request
- [x] claim this issue (comment below)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-account/blob/master/README.md#local-setup-and-tests)
- [x] Edit the `README.md` file.
- [x] Commit the change `docs(README): fixed local server URL`
- [x] Start a Pull Request.  Mention `closes #4` in the description of the pull request
- [x] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by caityc** [comment]
Claiming this

**Comment by caityc** [comment]
Pull request ready for review

**Comment by ghost** [comment]
claimed
